credentials:
  - "WdlP8F8gYr5sk^wf"
  - "NVX53zx7q%3SvhZ8"
  - "#wM7xQS1k6VXVtnq"
  - "IY=Y77hUaCejJlRt"
  - "2=iVZlbujkVQp41d"
  - "NsgGQR8P068M^jN5"
  - "bgHhRw8UVX-McP0F"
  - "u8@NiXt3gOVpAqQH"
  - "VsuOXxeLv3@Jag6D"
  - "9%vsJKoP1g6rJWm1"
  - "lZ9dYi83sZ4#hpCH"
  - "@Sy9aNscEsmdN3J4"
  - "@eZOIc7jRwfFnJ1J"
  - "8Ft@7dZIm8psxv2x"
  - "8-JpVP0ECajO1EN0"
  - "5GoZ9NFVkEZ7YoG#"
  - "j9h8XfOXz%KYz7hB"
  - "5+vkBDWlu8Cvh1Qv"
  - "z-hG3dfXSDQZZg04"
